// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBirg0f-UhjW259y6f8590tep4YfDB1pIQ',
    appId: '1:563751850651:web:95c171417ed62e0727ec3e',
    messagingSenderId: '563751850651',
    projectId: 'fruits-app-a28b5',
    authDomain: 'fruits-app-a28b5.firebaseapp.com',
    storageBucket: 'fruits-app-a28b5.firebasestorage.app',
    measurementId: 'G-SHQZ22WGZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM0KkOwJwg6p_b8ClqVCu3xcP6q2tp7ns',
    appId: '1:563751850651:android:3f9bc0d764c7a11b27ec3e',
    messagingSenderId: '563751850651',
    projectId: 'fruits-app-a28b5',
    storageBucket: 'fruits-app-a28b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJLxbO5OTNdnjWcRrSwwKtKGdt_kwpe8s',
    appId: '1:563751850651:ios:5b20f1a2a8b36ee727ec3e',
    messagingSenderId: '563751850651',
    projectId: 'fruits-app-a28b5',
    storageBucket: 'fruits-app-a28b5.firebasestorage.app',
    androidClientId: '563751850651-14oveh1e77qfovsl6igrivv3ovi0emq6.apps.googleusercontent.com',
    iosClientId: '563751850651-nu3qd9uhe4pu1l74esdv698q99crdnf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsAppDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJLxbO5OTNdnjWcRrSwwKtKGdt_kwpe8s',
    appId: '1:563751850651:ios:5b20f1a2a8b36ee727ec3e',
    messagingSenderId: '563751850651',
    projectId: 'fruits-app-a28b5',
    storageBucket: 'fruits-app-a28b5.firebasestorage.app',
    androidClientId: '563751850651-14oveh1e77qfovsl6igrivv3ovi0emq6.apps.googleusercontent.com',
    iosClientId: '563751850651-nu3qd9uhe4pu1l74esdv698q99crdnf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsAppDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBirg0f-UhjW259y6f8590tep4YfDB1pIQ',
    appId: '1:563751850651:web:d0309def75d6a92627ec3e',
    messagingSenderId: '563751850651',
    projectId: 'fruits-app-a28b5',
    authDomain: 'fruits-app-a28b5.firebaseapp.com',
    storageBucket: 'fruits-app-a28b5.firebasestorage.app',
    measurementId: 'G-0FQJJLBPSB',
  );
}
